# Generated by Django 4.2.1 on 2023-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_offer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='subject',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='receiver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
