# Generated by Django 4.2.1 on 2023-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_offer_price_offer_receiver_offer_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=10),
        ),
    ]
