# Generated by Django 4.2.1 on 2023-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sender',
            field=models.CharField(null=True),
        ),
    ]
