# Generated by Django 4.2.1 on 2023-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_offer_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.CharField(null=True),
        ),
    ]
