# Generated by Django 4.2.1 on 2023-07-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_offer_sender_alter_review_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='senderID',
            field=models.IntegerField(null=True),
        ),
    ]
