const DUMMY_DATA = [
    { id: "1", 
      uri: require("../assets/dp1.jpg"),
      name: "William",
      age: "25",
      subjects: ["Secondary English", "Secondary A Math"],
      gender: "M",
      price: "$30-40",
      locations: ['Southwest', 'North'],
      experience: "3 years",
  },
    { id: "2", 
      uri: require("../assets/dp2.jpg"),
      name: "John",
      age: "21",
      subjects: ["Primary Chinese", "Primary Malay"],
      gender: "M",
      price: "$20-30",
      locations: ['West', 'Central'],
      experience: "2 years",
    },
    { id: "3", 
      uri: require("../assets/dp3.jpg"),
      name: "Kelly",
      age: "24",
      subjects: ["Secondary History", "Secondary Malay"],
      gender: "M",
      price: "$35-50",
      locations: ['East', 'Central'],
      experience: "4 years",
    },
    { id: "4", 
    uri: require("../assets/dp4.jpg"),
    name: "Tim",
    age: "27",
    subjects: ["Grade 5 Music"],
    gender: "M",
    price: "$20-30",
    locations: ['West', 'Central'],
    experience: "NIL",
    },
    { id: "5", 
    uri: require("../assets/dp5.jpg"),
    name: "Grace",
    age: "31",
    subjects: ["Secondary Geography", "Secondary E Math"],
    gender: "F",
    price: "$35-50",
    locations: ['East'],
    experience: "4 years",
    },
  ]

export default DUMMY_DATA;